int getchar1(void);
int getchar2(void);
void test_getchar1();
void test_getchar2();
void test_print_ls(int,char**);
void print_ls(char *);
void liste_rep(char *);
void test_liste_rep(int,char **);
int is_dir(char *);
void vider_chaine(char *);
void lecture_entree_standard_fonctions_bibliotheque();
void lecture_entree_standard_primitives_systeme(int);
int recherche_dichotomique(char *);
void test_recherche_dichotomique();
