#!/bin/bash

mypwd=`pwd` # $(pwd)
var=13

#	if [ condition ] 
#	then
#		...
#	elif [ condition ]
#		...
#	else
#		...
#	fi
#	
#	for var in `seq 1 1000`
#	do
#		...
#	done

## EXAMPLES

# echo ${mypwd}
# echo $(pwd)

#	[ ${var} = "truc" ] && echo "COUCOU" || echo "bidule"
#	
#	-eq = ; -gt > ; -ge >= ; -lt < ; -le <= ; -ne != 
#	[ 0 -eq ${var} ] && echo "la variable ${var} vaut 0" || echo "ou pas"

#	for i in $(seq 1 1000)
#	do
#		echo $i
#		[ $i -eq 10 ] && break
#	done

