-- Ce script supprime toutes les tables et toutes les contraintes

-- Suppression des FK en premier
ALTER TABLE CLIENT			DISABLE 	CONSTRAINT u_client_nom_prenom_adresse ;
ALTER TABLE VILLE			DISABLE 	CONSTRAINT u_ville_nomVille ;
ALTER TABLE ESCALE			DISABLE 	CONSTRAINT u_escale ;
ALTER TABLE ESCALE			DISABLE 	CONSTRAINT ck_escale_villes_differentes ;
ALTER TABLE ESCALE			DISABLE 	CONSTRAINT fk_escale_villedepart ;
ALTER TABLE ESCALE			DISABLE 	CONSTRAINT fk_escale_villearrivee ;
ALTER TABLE VOL				DISABLE 	CONSTRAINT fk_vol_compagnie ;
ALTER TABLE VOL				DISABLE 	CONSTRAINT fk_vol_villedepart ;
ALTER TABLE VOL				DISABLE 	CONSTRAINT fk_vol_villearrivee ;
ALTER TABLE VOL				DISABLE 	CONSTRAINT ck_vol_nbbillets ;
ALTER TABLE BILLET			DISABLE 	CONSTRAINT ck_billet_etatbillet ;
ALTER TABLE BILLET			DISABLE 	CONSTRAINT ck_billet_prix ;
ALTER TABLE BILLET			DISABLE 	CONSTRAINT fk_billet_vol_compagnie ;
ALTER TABLE BILLET_CLIENT 	DISABLE 	CONSTRAINT fk_billet_client_client ;
ALTER TABLE BILLET_CLIENT 	DISABLE 	CONSTRAINT fk_billet_client_billet ;
ALTER TABLE CARTE_FIDELITE 	DISABLE 	CONSTRAINT fk_carte_fidelite_compagnie ;
ALTER TABLE CARTE_FIDELITE 	DISABLE 	CONSTRAINT fk_carte_fidelite_client ;
ALTER TABLE RESERVATION 	DISABLE 	CONSTRAINT fk_reservation_client ;
ALTER TABLE RESERVATION 	DISABLE 	CONSTRAINT fk_reservation_billet ;
ALTER TABLE VOL_ESCALE		DISABLE 	CONSTRAINT fk_vol_escale_vol ;
ALTER TABLE VOL_ESCALE		DISABLE 	CONSTRAINT fk_vol_escale_escale ;

-- Suppression des PK en second
ALTER TABLE CLIENT			DISABLE 	CONSTRAINT pk_client ;
ALTER TABLE COMPAGNIE		DISABLE 	CONSTRAINT pk_compagnie ;
ALTER TABLE VOL_ESCALE		DISABLE 	CONSTRAINT pk_vol_escale ;
ALTER TABLE RESERVATION		DISABLE 	CONSTRAINT pk_reservation ;
ALTER TABLE BILLET_CLIENT 	DISABLE 	CONSTRAINT pk_billet_client ;
ALTER TABLE BILLET			DISABLE 	CONSTRAINT pk_billet ;
ALTER TABLE VOL				DISABLE 	CONSTRAINT pk_vol ;
ALTER TABLE ESCALE			DISABLE 	CONSTRAINT pk_escale ;
ALTER TABLE VILLE			DISABLE 	CONSTRAINT pk_ville ;
ALTER TABLE CARTE_FIDELITE 	DISABLE 	CONSTRAINT pk_carte_fidelite ;

-- Suppression des tables en dernier
DROP TABLE  CLIENT ;
DROP TABLE  VILLE ;
DROP TABLE  COMPAGNIE ;
DROP TABLE  ESCALE ;
DROP TABLE  VOL ;
DROP TABLE  BILLET ;
DROP TABLE  BILLET_CLIENT ;
DROP TABLE  CARTE_FIDELITE ;
DROP TABLE  RESERVATION ;
DROP TABLE  VOL_ESCALE ;
