-- Ce script supprime toutes les tables et toutes les contraintes

-- Suppression des FK en premier, avec les autres contraintes
ALTER TABLE CLIENT			DROP 	CONSTRAINT u_client_nom_prenom_adresse ;
ALTER TABLE CLIENT			DROP 	CONSTRAINT u_client_login;
ALTER TABLE GESTIONNAIRE	DROP	CONSTRAINT fk_gestionnaire_compagnie;
ALTER TABLE GESTIONNAIRE	DROP	CONSTRAINT u_gestionnaire_login;
ALTER TABLE VILLE			DROP 	CONSTRAINT u_ville_nomVille ;
ALTER TABLE ESCALE			DROP 	CONSTRAINT fk_escale_ville;
ALTER TABLE ESCALE			DROP 	CONSTRAINT fk_escale_vol ;
ALTER TABLE VOL				DROP	CONSTRAINT ck_vol_dates ; 
ALTER TABLE VOL				DROP	CONSTRAINT ck_vol_villes ; 
ALTER TABLE VOL				DROP 	CONSTRAINT fk_vol_compagnie ;
ALTER TABLE VOL				DROP 	CONSTRAINT fk_vol_villedepart ;
ALTER TABLE VOL				DROP 	CONSTRAINT fk_vol_villearrivee;
ALTER TABLE BILLET			DROP 	CONSTRAINT ck_billet_etatbillet ;
ALTER TABLE BILLET			DROP 	CONSTRAINT ck_billet_prix ;
ALTER TABLE BILLET			DROP 	CONSTRAINT fk_billet_vol_compagnie ;
ALTER TABLE BILLET_CLIENT 	DROP 	CONSTRAINT fk_billet_client_client ;
ALTER TABLE BILLET_CLIENT 	DROP 	CONSTRAINT fk_billet_client_billet ;
ALTER TABLE CARTE_FIDELITE 	DROP 	CONSTRAINT fk_carte_fidelite_compagnie ;
ALTER TABLE CARTE_FIDELITE 	DROP 	CONSTRAINT fk_carte_fidelite_client ;
ALTER TABLE RESERVATION 	DROP 	CONSTRAINT fk_reservation_client ;
ALTER TABLE RESERVATION 	DROP 	CONSTRAINT fk_reservation_billet ;
ALTER TABLE ARCHIVES		DROP	CONSTRAINT fk_archives_client ;
ALTER TABLE ARCHIVES		DROP	CONSTRAINT fk_archives_vol ;
ALTER TABLE ARCHIVES		DROP	CONSTRAINT fk_archives_billet ;

-- Suppression des PK en second
ALTER TABLE CLIENT			DROP 	CONSTRAINT pk_client ;
ALTER TABLE COMPAGNIE		DROP 	CONSTRAINT pk_compagnie ;
ALTER TABLE GESTIONNAIRE	DROP	CONSTRAINT pk_gestionnaire;
ALTER TABLE RESERVATION		DROP 	CONSTRAINT pk_reservation ;
ALTER TABLE BILLET_CLIENT 	DROP 	CONSTRAINT pk_billet_client ;
ALTER TABLE BILLET			DROP 	CONSTRAINT pk_billet ;
ALTER TABLE VOL				DROP 	CONSTRAINT pk_vol ;
ALTER TABLE ESCALE			DROP 	CONSTRAINT pk_escale ;
ALTER TABLE VILLE			DROP 	CONSTRAINT pk_ville ;
ALTER TABLE CARTE_FIDELITE 	DROP 	CONSTRAINT pk_carte_fidelite ;
ALTER TABLE ARCHIVES		DROP	CONSTRAINT pk_archives ;

-- Suppression des tables en dernier
DROP TABLE  CLIENT ;
DROP TABLE  VILLE ;
DROP TABLE  GESTIONNAIRE ;
DROP TABLE  COMPAGNIE ;
DROP TABLE  ESCALE ;
DROP TABLE  VOL ;
DROP TABLE  BILLET ;
DROP TABLE  BILLET_CLIENT ;
DROP TABLE  CARTE_FIDELITE ;
DROP TABLE  RESERVATION ;
DROP TABLE  ARCHIVES ;

-- Suppression des séquences
DROP SEQUENCE seq_client ;
DROP SEQUENCE seq_gestionnaire ;
DROP SEQUENCE seq_billet ;
DROP SEQUENCE seq_billet_client ;
DROP SEQUENCE seq_ville ;
DROP SEQUENCE seq_compagnie ;
DROP SEQUENCE seq_escale ;
DROP SEQUENCE seq_archives ;
