
all :
	set -v
	javac *.java
	rmic AnnuaireImpl

clean : 
	rm -f *~ *.class

#
# rmiregistry 10000
# java AnnuaireImpl 10000
# appletviewer AppletClient.html
#
# appletviewer AppletClient.html
#
# OU : 
# java Ajoute nom num
# java Supprime nom
#
#
#
