// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

public final class MessageImpl_Stub
    extends java.rmi.server.RemoteStub
    implements Message, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_messageDistant_0;
    
    static {
	try {
	    $method_messageDistant_0 = Message.class.getMethod("messageDistant", new java.lang.Class[] {});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public MessageImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of messageDistant()
    public java.lang.String messageDistant()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_messageDistant_0, null, 6077153416669044887L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
