
/**
* IcarreOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Icarre.idl
* vendredi 26 octobre 2012 11 h 30 CEST
*/

public interface IcarreOperations 
{
  int carre (int source);
} // interface IcarreOperations
