
/**
* Icarre.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Icarre.idl
* vendredi 26 octobre 2012 11 h 30 CEST
*/

public interface Icarre extends IcarreOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Icarre
