
/**
* Icarre.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Icarre.idl
* vendredi 16 novembre 2012 10 h 21 CET
*/

public interface Icarre extends IcarreOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Icarre
