
/**
* IcarreHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Icarre.idl
* vendredi 26 octobre 2012 11 h 30 CEST
*/

abstract public class IcarreHelper
{
  private static String  _id = "IDL:Icarre:1.0";

  public static void insert (org.omg.CORBA.Any a, Icarre that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Icarre extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (IcarreHelper.id (), "Icarre");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Icarre read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_IcarreStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Icarre value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Icarre narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Icarre)
      return (Icarre)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _IcarreStub stub = new _IcarreStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Icarre unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Icarre)
      return (Icarre)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _IcarreStub stub = new _IcarreStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
