graph [
   comment "Generated by ViSiDiA" 
   node [
      id 0
      graphics [
         x 122
         y 99
      ]
   ]
   node [
      id 1
      graphics [
         x 462
         y 191
      ]
   ]
   node [
      id 2
      graphics [
         x 204
         y 276
      ]
   ]
   node [
      id 3
      graphics [
         x 383
         y 50
      ]
   ]
   edge [
      source 2
      target 3
   ]
   edge [
      source 0
      target 3
   ]
   edge [
      source 1
      target 2
   ]
   edge [
      source 0
      target 3
   ]
   edge [
      source 1
      target 2
   ]
   edge [
      source 1
      target 3
   ]
   edge [
      source 0
      target 1
   ]
   edge [
      source 0
      target 2
   ]
]